apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  labels: { app: django-app }
spec:
  replicas: {{ .Values.hpa.minReplicas }}
  selector:
    matchLabels: { app: django-app }
  template:
    metadata:
      labels: { app: django-app }
    spec:
      containers:
        - name: django
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          envFrom:
            - configMapRef:
                name: django-app-config
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 30
            periodSeconds: 30
